### ISSUE TITLE
Version 4.4.0?

### ISSUE THREAD

**Issue by LeBaron90** [g30r93g/homebridge-panasonic#11]
Hi,

The highest version I can install is 4.3.2, but on your readme.txt is v.4.4.0.

Is 4.3.2 the latest version? Apple just announced iOS 12.3: so TVs are now officially supported. Is there a way to add AirPlay2 too?

thanks

**Comment by g30r93g** [comment]
Hi!

v 4.4.0 is now up. Forgot to enter npm pub earlier this week 😂
Hopefully it works properly.
TV's should work properly though I haven't had time to play around with their iOS 12.3 behaviour just yet so I'll update the README if there is something.

I really want AirPlay 2 as well but that is a separate protocol and we need to wait for someone else to reverse engineer it. Hopefully that'll be soon!

Hope this clears up a few things!
