### ISSUE TITLE
TV Remote

### ISSUE THREAD

**Issue by g30r93g** [g30r93g/homebridge-panasonic#12]
Turns off the TV before performing commands.

**Comment by James712346** [comment]
found that m4recek/panasonic-viera-remote-control library uses different command to you

	VieraTVRemote.COMMANDS = [
	'NRC_POWER-ONOFF',		// power off only (on tested TV)

	'NRC_MUTE-ONOFF',
	'NRC_AD_CHANGE-ONOFF',	// dvbt input change
	'NRC_CHG_INPUT-ONOFF',	// hdmi input change

	'NRC_VOLDOWN-ONOFF',	// separate ON and OFF commands exists, can be used instead repeating ONOFF
	'NRC_VOLDOWN-ON',
	'NRC_VOLDOWN-OFF',
	'NRC_VOLUP-ONOFF',		// separate ON and OFF commands exists, can be used instead repeating ONOFF
	'NRC_VOLUP-ON',
	'NRC_VOLUP-OFF',

	'NRC_CH_DOWN-ONOFF',
	'NRC_CH_UP-ONOFF',

	'NRC_APPS-ONOFF',
	'NRC_HOME-ONOFF',
	'NRC_CANCEL-ONOFF',		// exit button

	'NRC_RIGHT-ONOFF',		// separate ON and OFF commands exists, can be used instead repeating ONOFF
	'NRC_RIGHT-ON',
	'NRC_RIGHT-OFF',

	'NRC_LEFT-ONOFF',		// separate ON and OFF commands exists, can be used instead repeating ONOFF
	'NRC_LEFT-ON',
	'NRC_LEFT-OFF',

	'NRC_DOWN-ONOFF',		// separate ON and OFF commands exists, can be used instead repeating ONOFF
	'NRC_DOWN-ON',
	'NRC_DOWN-OFF',

	'NRC_UP-ONOFF',			// separate ON and OFF commands exists, can be used instead repeating ONOFF
	'NRC_UP-ON',
	'NRC_UP-OFF',

	'NRC_ENTER-ONOFF',		// ok button
	'NRC_RETURN-ONOFF',
	'NRC_SUBMENU-ONOFF',	// options button

	'NRC_3D-ONOFF',
	'NRC_DISP_MODE-ONOFF',	// aspect button
	'NRC_MENU-ONOFF',
	'NRC_EPG-ONOFF',		// guide button
	'NRC_TEXT-ONOFF',
	'NRC_STTL-ONOFF',
	'NRC_INFO-ONOFF',
	'NRC_GUIDE-ONOFF',		// e-help button

	'NRC_D1-ONOFF',
	'NRC_D2-ONOFF',
	'NRC_D3-ONOFF',
	'NRC_D4-ONOFF',
	'NRC_D5-ONOFF',
	'NRC_D6-ONOFF',
	'NRC_D7-ONOFF',
	'NRC_D8-ONOFF',
	'NRC_D9-ONOFF',
	'NRC_D0-ONOFF',
	'NRC_R_TUNE-ONOFF',		// last view button

	'NRC_BLUE-ONOFF',		// quick commands and teletext controls (based on context)
	'NRC_YELLOW-ONOFF',
	'NRC_GREEN-ONOFF',
	'NRC_RED-ONOFF',

	'NRC_REW-ONOFF',
	'NRC_PLAY-ONOFF',
	'NRC_FF-ONOFF',
	'NRC_SKIP_PREV-ONOFF',
	'NRC_PAUSE-ONOFF',
	'NRC_SKIP_NEXT-ONOFF',
	'NRC_STOP-ONOFF',
	'NRC_REC-ONOFF'
	'];
could this be the problem?

**Comment by James712346** [comment]
I also tried these command on postman and they all work with my TV
![image](https://user-images.githubusercontent.com/33794556/59970047-5aab6a00-95a0-11e9-80a5-08e1f10328cf.png)
![image](https://user-images.githubusercontent.com/33794556/59970057-73b41b00-95a0-11e9-9ed4-3cf65f523e91.png)

**Comment by muenzpraeger** [comment]
@James712346 The `viera.js` package that's used here uses the same codes as you referenced above. The implementation is [simplified](https://github.com/samuelmatis/viera.js/blob/b3aaf425c50a576833bd13b65392484c0e9cb162/viera.js#L94) though.

**Comment by g30r93g** [comment]
Hi there. I’ve seen many other commands that have the same behaviour. If the existing command doesn’t work for you but the commands via Postman do, then please respond here so I can look into how to solving this. Many thanks!

**Comment by muenzpraeger** [comment]
The issue is that after the `remoteKey` call immediately `setOn` is called. As it's not in your code I'm wondering if that's intentionally (by HomeKit), and you'd need some other logic or state management.

**Comment by muenzpraeger** [comment]
@g30r93g The behavior also exists with iOS 13, just FYI.

**Comment by muenzpraeger** [comment]
@g30r93g The last iOS 13 beta fixed everything. Works fine!

**Comment by g30r93g** [comment]
Great to hear! Do open this up if it stops again.
