### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by LeBaron90** [g30r93g/homebridge-panasonic#15]
Hey

At first, thank you very much for developing that plugin nearly every day :)

For me, Netflix, YouTube and Apple TV works great.

The issue I have is: TV
My Panasonic don't change to "TV" when I press "TV" as input.

Nice to have's:

- AccuWeather
- MyApp (you can call it maybe "Favourite App"
- TuneIn (not for me, but maybe for guys who use this)

For all other guys here, you see images of the version 6.0.1 as attachment.

regards
![IMG_0683](https://user-images.githubusercontent.com/15858705/58050156-de5fda00-7b4e-11e9-8125-155c84a5fc1a.PNG)
![IMG_0682](https://user-images.githubusercontent.com/15858705/58050158-de5fda00-7b4e-11e9-8236-60de0b2a6ba0.PNG)
![IMG_0681](https://user-images.githubusercontent.com/15858705/58050160-de5fda00-7b4e-11e9-9e07-7085a81a03b4.PNG)
![IMG_0680](https://user-images.githubusercontent.com/15858705/58050162-def87080-7b4e-11e9-8d66-621a4d2bdb2a.PNG)
![IMG_0679](https://user-images.githubusercontent.com/15858705/58050163-def87080-7b4e-11e9-987b-3f64d1d9608d.PNG)

**Comment by LeBaron90** [comment]
I found the appID for AccuWeather, here is the line:

      {"id" : "AccuWeather.com", "name": "AccuWeather.com", "type": "APPLICATION", "appID": "0070000C00000001"}


But now I see the AccuWeather like this (see attachment).
![IMG_0685](https://user-images.githubusercontent.com/15858705/58051267-013fbd80-7b52-11e9-82bf-daa83e536f14.PNG)
![IMG_0684](https://user-images.githubusercontent.com/15858705/58051268-013fbd80-7b52-11e9-88ca-009d7aaca962.PNG)

**Comment by g30r93g** [comment]
Hi! Sorry for being slow to reply. This has happened to me as well but I haven't found a way around it other than relaunching the home app. Eventually it will disappear but that's not good enough on my side so I'll look into it soon!

**Comment by g30r93g** [comment]
So after playing around I can see what's going on. The TV doesn't want to switch to the TV input when inside an application, which is quite frankly, ridiculous. I'll try a few things to see if I can change this.

**Comment by LeBaron90** [comment]
It disappeared, now I see it as input - so that's ok for me. no changes needed for me. 
But changing the input while the TV is inside an application would be nice. thank you :)

**Comment by g30r93g** [comment]
Done!
Should work on 6.1.0

**Comment by LeBaron90** [comment]
thank you for the fast update, I can confirm it - it works now.

**Comment by g30r93g** [comment]
I think the app showing as a phantom device is a HomeKit thing so I’ll close this for now but if I do figure it out I’ll be sure to let you know here!
