### ISSUE TITLE
Panasonic TX-55CXW754 not supported?

### ISSUE THREAD

**Issue by albi** [g30r93g/homebridge-panasonic#16]
Having a 2015 model of Panasonic, I can't get the switch to turn on the TV although the plugin https://www.npmjs.com/package/homebridge-panasonictv is already running without problems in Homebdrige. So network on/off is working with my TV. Is there anything I forgot?

**Comment by g30r93g** [comment]
Hi!
The plugin https://www.npmjs.com/package/homebridge-panasonictv may be clashing.
Perform `sudo npm uninstall -g homebridge-panasonictv` and remove the config for that plugin from your `config.json` file.
Let me know if this fixes your problem!

**Comment by albi** [comment]
Unfortunately it did not help.

The log says

`[2019-5-24 20:33:22] [TV] Powering TV on...
error: connect EHOSTUNREACH 10.0.0.7:55000
{ Error: connect EHOSTUNREACH 10.0.0.7:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.0.0.7',
  port: 55000 }
error: connect EHOSTUNREACH 10.0.0.7:55000
{ Error: connect EHOSTUNREACH 10.0.0.7:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.0.0.7',
  port: 55000 }
    root : TTY=pts/0 ; PWD=/var/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
[2019-5-24 20:33:42] [TV] Couldn't check power state. Please check your TV's network connection.
[2019-5-24 20:33:42] [TV] Alternatively, your TV may not be correctly set up or it may not be able to perform power on from standby.`

But the other plugins can switch the TV on and off. So everything seems to be fine on the network and TV.

**Comment by albi** [comment]
Sorry had a typo in my IP address! It helped getting rid of the other plugin! THX!

**Comment by g30r93g** [comment]
Great to hear! Hope you enjoy future releases!

**Comment by albi** [comment]
for sure! thx for your efforts
