### ISSUE TITLE
TV not seen on alternate Home Apps

### ISSUE THREAD

**Issue by LeBaron90** [g30r93g/homebridge-panasonic#17]
Hi,

The powerfull „Eve“ app or the „Devices“ app can‘t see the TV. In the standard „Home“ app I can see the TV. 
Any ideas how to get that fixed?
Thanks

**Comment by albi** [comment]
same problem here

**Comment by g30r93g** [comment]
Hi! 
This is most likely to do with the Eve app. I haven’t seen any other TV’s show up in there so I don’t think it is an issue with this plugin.
I do suggest leaving a review on the Eve app in the respective App Store that you use to push their devs for this feature.
