### ISSUE TITLE
YouTube won't open

### ISSUE THREAD

**Issue by albi** [g30r93g/homebridge-panasonic#18]
On my TV the YouTube App won't open. Plex and Recorded TV are working as well as the TV input. Maybe it is another appID?

**Comment by g30r93g** [comment]
Hi! Sorry for the slow reply. It may very well be and I wouldn't be able to help you unless you could do the following:
1. Install Wireshark
2. Install Panasonic TV on your mobile device
3. Use your mobile device as a network interface in Wireshark
4. Use the Panasonic TV app to open YouTube
5. Filter results by 'http' and find the request to open YouTube (It will be in the XML with a tag called `X_LaunchApp`)
6. Find the app ID. It will look something like `<X_LaunchKeyword>product_id=000000000</X_LaunchKeyword>` The `product_id` is the app ID

**Comment by g30r93g** [comment]
This might sound a bit obvious but copy and paste the app ID into your `config.json` file and restart homebridge and see what happens

**Comment by albi** [comment]
I would like to help, but I am a bit lost inside Wireshark. I do scan the traffic of my iPhone but can't find any http request. Maybe the traffic is secured? Can find some TLSv1.2 data.

**Comment by Derky** [comment]
@albi can you try this App ID for YouTube: `0070000200000001`
Works for my Panasonic TX-40CX720

@g30r93g I've also created a PR for adding this ID and a few more: https://github.com/g30r93g/homebridge-panasonic/pull/24

**Comment by g30r93g** [comment]
Hi guys. Please reopen this if you still have any issues. However, hopefully @Derky has fixed the issue with the multiple app ID's that YouTube has.
