### ISSUE TITLE
6.2.0 broke homebridge

### ISSUE THREAD

**Issue by NogginTheNog** [g30r93g/homebridge-panasonic#26]
6.2.0 broke homebridge, was working fine with the previous version.

Nov 03 19:18:27 homebridge homebridge[19694]: [2019-11-3 19:18:27] [Living Room TV] Initializing Panasonic-TV accessory...
**Nov 03 19:18:27 homebridge homebridge[19694]: [2019-11-3 19:18:27] TypeError: You entered invalid IP address!**
Nov 03 19:18:27 homebridge homebridge[19694]:     at new Viera (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/viera.js/viera.js:22:19)
Nov 03 19:18:27 homebridge homebridge[19694]:     at PanasonicTV.getServices (/usr/lib/node_modules/homebridge-panasonic-viera-tv/index.js:36:15)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
Nov 03 19:18:27 homebridge homebridge[19694]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Module._compile (module.js:653:30)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Object.Module._extensions..js (module.js:664:10)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Module.load (module.js:566:32)
Nov 03 19:18:27 homebridge homebridge[19694]:     at tryModuleLoad (module.js:506:12)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Function.Module._load (module.js:498:3)
Nov 03 19:18:27 homebridge homebridge[19694]:     at Function.Module.runMain (module.js:694:10)
Nov 03 19:18:27 homebridge homebridge[19694]:     at startup (bootstrap_node.js:204:16)
Nov 03 19:18:27 homebridge homebridge[19694]:     at bootstrap_node.js:625:3
Nov 03 19:18:27 homebridge homebridge[19694]: [2019-11-3 19:18:27] Got SIGTERM, shutting down Homebridge...
Nov 03 19:18:27 homebridge homebridge[19694]: [2019-11-3 19:18:27] [Car] Looking for Bluetooth devices

Config:-

        {
            "accessory": "Panasonic-TV",
            "name": "Living Room TV",
            "ipaddress": "172.16.4.11",
            "inputs": [
                {
                    "id": "TV",
                    "name": "TV",
                    "type": "TV"
                },
                {
                    "id": "HDMI 1",
                    "name": "Xbox",
                    "type": "HDMI"
                },
                {
                    "id": "HDMI 2",
                    "name": "Apple TV",
                    "type": "HDMI"
                },
                {
                    "id": "HDMI 3",
                    "name": "HDMI 3",
                    "type": "HDMI"
                },
                {
                    "id": "BBC iPlayer",
                    "name": "BBC iPlayer",
                    "type": "APPLICATION",
                    "appID": "0020000A00170010"
                },
                {
                    "id": "Netflix",
                    "name": "Netflix",
                    "type": "APPLICATION",
                    "appID": "0010000200000001"
                }
            ]
        },

**Comment by g30r93g** [comment]
Sorry, I've just seen it. My code style linter told me to change ipaddress to ipAddress. I'll change it back right now.
