### ISSUE TITLE
TV Power Reporting (X_ScreenState)

### ISSUE THREAD

**Issue by g30r93g** [g30r93g/homebridge-panasonic#32]
I may have fixed the crashing due to X_ScreenState. Putting out a new version in the next 30 mins.

**Comment by g30r93g** [comment]
New version released. Please update to 6.3.0 using `sudo npm install -g homebridge-panasonic-viera-tv@6.3.0`

**Comment by machineglow** [comment]
Hi,

Tried installing this plugin today and ran into this issue.  I have one of the earlier Panasonic tv's that don't respond when turned off (TC-P65ST50).   Strangely enough, my TV *is* on right now and it's still failing with this error.  So I think our older TVs simply do not have the X_ScreenState property.   I'm on 6.3.0 as well.  

I took a look at the other homebridge-panasonictv plugin (I was using this previously and it would report on when on and off all other times) and it looks like it's doing a general state query and using that.   

Thanks!

`[4/18/2020, 11:57:18 AM] TypeError: Cannot read property 'X_ScreenState' of undefined
Apr 18 11:57:18 homiebee homebridge[6945]:     at Subscription.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/index.js:258:53)
Apr 18 11:57:18 homiebee homebridge[6945]:     at Subscription.emit (events.js:315:20)
Apr 18 11:57:18 homiebee homebridge[6945]:     at /usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/node-upnp-subscription/index.js:37:37
Apr 18 11:57:18 homiebee homebridge[6945]:     at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:304:18)
Apr 18 11:57:18 homiebee homebridge[6945]:     at Parser.emit (events.js:315:20)
Apr 18 11:57:18 homiebee homebridge[6945]:     at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:262:26)
Apr 18 11:57:18 homiebee homebridge[6945]:     at emit (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:624:35)
Apr 18 11:57:18 homiebee homebridge[6945]:     at emitNode (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:629:5)
Apr 18 11:57:18 homiebee homebridge[6945]:     at closeTag (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:889:7)
Apr 18 11:57:18 homiebee homebridge[6945]:     at SAXParser.write (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:1436:13)
Apr 18 11:57:18 homiebee homebridge[6945]:     at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:323:31)
Apr 18 11:57:18 homiebee homebridge[6945]:     at Parser.parseString (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:5:59)
Apr 18 11:57:18 homiebee homebridge[6945]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/parsexmlresponse/index.js:15:23)
Apr 18 11:57:18 homiebee homebridge[6945]:     at IncomingMessage.emit (events.js:327:22)
Apr 18 11:57:18 homiebee homebridge[6945]:     at endReadableNT (_stream_readable.js:1201:12)
Apr 18 11:57:18 homiebee homebridge[6945]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

**Comment by g30r93g** [comment]
Hi. Please update the plugin and see if it'll work. There's been some issues with power reporting and maybe you'll be able to see it?

**Comment by machineglow** [comment]
Hmm..  

I upgraded and I still get the same error. 

```
May 10 20:55:50 homiebee homebridge[2047]: [5/10/2020, 8:55:50 PM] TypeError: Cannot read property 'X_ScreenState' of undefined
May 10 20:55:50 homiebee homebridge[2047]:     at Subscription.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/index.js:265:53)
May 10 20:55:50 homiebee homebridge[2047]:     at Subscription.emit (events.js:315:20)
May 10 20:55:50 homiebee homebridge[2047]:     at /usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/node-upnp-subscription/index.js:37:37
May 10 20:55:50 homiebee homebridge[2047]:     at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:304:18
)
May 10 20:55:50 homiebee homebridge[2047]:     at Parser.emit (events.js:315:20)
May 10 20:55:50 homiebee homebridge[2047]:     at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:262:
26)
May 10 20:55:50 homiebee homebridge[2047]:     at emit (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:624:35)
May 10 20:55:50 homiebee homebridge[2047]:     at emitNode (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:629:5)
May 10 20:55:50 homiebee homebridge[2047]:     at closeTag (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:889:7)
May 10 20:55:50 homiebee homebridge[2047]:     at SAXParser.write (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:1436:13)
May 10 20:55:50 homiebee homebridge[2047]:     at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2j
s/lib/parser.js:323:31)
May 10 20:55:50 homiebee homebridge[2047]:     at Parser.parseString (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:5:59)
May 10 20:55:50 homiebee homebridge[2047]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/parsexmlresponse/i
ndex.js:15:23)
May 10 20:55:50 homiebee homebridge[2047]:     at IncomingMessage.emit (events.js:327:22)
May 10 20:55:50 homiebee homebridge[2047]:     at endReadableNT (_stream_readable.js:1201:12)
May 10 20:55:50 homiebee homebridge[2047]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
May 10 20:55:50 homiebee homebridge[2047]: [5/10/2020, 8:55:50 PM] Got SIGTERM, shutting down Homebridge...
```

looks like the isArray() check isn't enough.  the properties is an array, but the screenstate just doesn't exist in that array I guess?


Let me know if there's any debug instrucitons you'd like me to run.

Thanks,
