### ISSUE TITLE
Issue with powering ON

### ISSUE THREAD

**Issue by ArielZgo** [g30r93g/homebridge-panasonic#33]
Hi, I receive this issue when Powering On. Do you know what is the problem?

error: connect EHOSTUNREACH MY_TV_IP:55000
{ Error: connect EHOSTUNREACH MY_TV_IP:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: 'MY_TV_IP',
  port: 55000 }

**Comment by g30r93g** [comment]
Hi.
You haven’t updated the config.json file with your TV’s IP address. Please do so and restart homebridge and it should work.

**Comment by ArielZgo** [comment]
Hey, I did. Just wrote down My_TV_IP not to share it. I can turn it off, but when I turn on I receive this error. Deleted and added again, but still the same issue.

**Comment by g30r93g** [comment]
Can you also make sure your TV works with the Panasonic TV remote app and you can turn it on and off in there? It may also require a change of setting on your TV. The error says the TV is unreachable meaning either the IP is wrong or you need to activate the relevant settings outlined in the readme of this repository (networked standby, tv remote settings, etc.)

**Comment by ArielZgo** [comment]
Thanks, I only see TV Remote. There are no more options. Also, from the app I can turn it off, but can't turn it on. So I suspect that's it :(
