### ISSUE TITLE
compatibility to homebridge v.1.0.0

### ISSUE THREAD

**Issue by z-smoker** [g30r93g/homebridge-panasonic#35]
Unfortunately, this plugin cannot work with the current version of Homebridge (V.1.0.0). Please could you adapt it. Thanks a lot in advance

**Comment by gonzague** [comment]
Oh I was wondering like a lunatic why it wasn't sending any commands to my TV .. haha :-)

**Comment by g30r93g** [comment]
Should be fixed now. Please confirm by updating to plugin version 7.0.0 and commenting here and I'll close the issue.

**Comment by g30r93g** [comment]
I am aware that during setup you'll get a message saying:
`Plugin 'homebridge-panasonic-viera-tv' tried to register with an incorrect plugin identifier: 'homebridge-panasonic'. Please report this to the developer!`
Just ignore this as it wants me to change the identifier to the plugin name. It would be a breaking change that would cause too much stress. If it ain't broke, don't fix it am i right lol

**Comment by ceeeekay** [comment]
Works great - thanks!
