### ISSUE TITLE
Define the Remote Buttons in the config.json file

### ISSUE THREAD

**Issue by julian-hummel** [g30r93g/homebridge-panasonic#36]
Hello,
I have installed the plugin and it works fine for turning off the TV and switching inputs. I have the problem, that my apple home app only shows the power button, but no other controls like volume control. Do I have to define them in the config.json? And if, how can I do that? 
Cheers,
Julian

**Comment by g30r93g** [comment]
Hi. So there are parts in the HomeKit API that allow volume control and remote control. These have already been coded in to expose these controls to HomeKit. However, they're a bit temperamental and the volume control has almost never worked for me. The TV remote should show up in the 'Apple TV Remote' control centre tile as a controllable TV. Furthermore, the TV remote seems to turn the TV off whenever you toggle a control which is strange so for now, the TV remote is a work in progress.

**Comment by g30r93g** [comment]
Reference to issue #30

**Comment by fhb** [comment]
Maybe you could talk to the provider or look at the code of the plugin "https://github.com/AntonioMeireles/homebridge-vieramatic"? It has a more recent bug leading to it not appearing in the home app, but the remote control worked well and didn't turn off my tv on every command.
