### ISSUE TITLE
Legacy Input Control

### ISSUE THREAD

**Issue by ValoV83** [g30r93g/homebridge-panasonic#38]
I was wondering if it’s possible to configure the plugin to be able to switch to legacy analogue inputs like the AV1 and AV2 inputs if defined within the config.json?

**Comment by g30r93g** [comment]
yep. definitely possible. i’ll find out the inputs needed to send to the tv and update the code if need be

**Comment by ValoV83** [comment]
That would be brilliant if possible as I have a few legacy devices I’d like to automate 👍

I’m guessing the ability to change channels and adjust volume are not possible?

**Comment by g30r93g** [comment]
Channels, unfortunately not with the current API. Volume should work when your TV shows up in the TV remote control center toggle but it's unstable whenever I test it.

**Comment by g30r93g** [comment]
I've tried to find some direct AV switching but it seems the only way I can find is by cycling through the AV inputs :/

**Comment by ValoV83** [comment]
Shame direct AV switching doesn't seem possible. Thanks for trying to find a solution to define it like an HDMI input.

With the workaround you've found how would it work? Would it be a button within the tile on the Home app lime the Power On/Off or would it be within the input slider for TV and Defined HDMI Inputs?

**Comment by g30r93g** [comment]
It would act as a stateless switch, so you'd tap a tile and it would cycle through. At least that's how I've pictured it in my mind

**Comment by g30r93g** [comment]
I'll see if i can add it in for you.

**Comment by g30r93g** [comment]
So I've been playing around but it seems to be hit and miss and I wouldn't feel comfortable adding something half-baked. Sorry about that. If at some point I figure out the exact command I'll comment in here and let you know.
