### ISSUE TITLE
Error - "Configured Panasonic TV... with IP undefined."

### ISSUE THREAD

**Issue by Neverwhere8** [g30r93g/homebridge-panasonic#40]
I have all latest plugins, including homebridge-panasonic-viera-tv v7.2.0, but when homebridge service starts and the Panasonic TV accessory loads, it shows in the log that the Panasonic TV has "IP undefined."
After opening the iOS Home app, the homebridge log then shows:
 "[5/15/2020, 3:19:41 PM] [TV] Couldn't check power state. Please check your TV's network connection.
[5/15/2020, 3:19:41 PM] [TV] Alternatively, your TV may not be correctly set up or it may not be able to perform power on from standby."

The correct ip address for the tv is in the config file. 

My Panasonic TV is model TC-P65GT50.
I am able to both power on and power off this tv using the "Panasonic TV Remote 2" app on iOS over ethernet, so I would expect to be able to do the same using this plugin.
However, this plugin does not seem to recognize that the tv exits at my tv's ip address.

Can this Panasonic TV plugin be fixed to allow for power on and off of my Panasonic 65GT50?

Thank you.

**Comment by msbc42** [comment]
Just started to use HomeBridge today. Installed this plug-in and am having the same issues with a TH-65FZ950U.

TV works via Pano app but nothing happens with iOS Home.

Also have a HomeAssistant server which I can control the TV from - the HA plugin required a PIN code setup by the TV. Maybe this plug-in does not work for TV's without a similar pin code?

**Comment by g30r93g** [comment]
Hi there. Some newer Panasonic TVs use encrypted communications between the device and the TV. I won’t be able to implement this since i don’t have one of these TVs. To solve this, @AntonioMeireles created [homebridge-vieramatic](https://github.com/AntonioMeireles/homebridge-vieramatic). Hope this solves the pin code problem.
