### ISSUE TITLE
TV icon became a "house" icon in iOS 14

### ISSUE THREAD

**Issue by acresp** [g30r93g/homebridge-panasonic#43]
Hello,
Don't know if the plugin needs to be updated but since I updated to iOS 14, the icon of the accessory became tiny house 🙂 
![Capture d’écran   2020-09-18 à 10 42 22](https://user-images.githubusercontent.com/57019575/93577596-8502f780-f99c-11ea-8e5d-444ba92a3ed5.jpeg)
Kind regards and thank for your work

**Comment by ValoV83** [comment]
+1 I have exactly the same problem. 

I was told by HOOBS Support that:

> This is not a HOOBS issue. It’s a plugin issue. Please report it to the plugin developer on their GitHub page. It needs to be implemented in the plugin code

https://github.com/hoobs-org/HOOBS/issues/802

**Comment by acresp** [comment]
It seems that now the TVs need to be exposed as "external accessory" (no more "bridged"), hope this fantastic plugin will be updated in that way 🙂  For the moment the fact that is bridged impacts only the icon, but in the future it mays be deprecated totally

**Comment by g30r93g** [comment]
Hi all. I will be fixing this up as soon as my exams are over. Another 2 weeks and expect to see some activity on this plugin.

**Comment by ValoV83** [comment]
> Hi all. I will be fixing this up as soon as my exams are over. Another 2 weeks and expect to see some activity on this plugin.

Glad you are still actively developing your great plugin.....I was beginning to think maybe you’d stopped and was considering switching to another variant. 

Real life comes first.....Best of luck with your exams 👍

**Comment by acresp** [comment]
> Hi all. I will be fixing this up as soon as my exams are over. Another 2 weeks and expect to see some activity on this plugin.

Nice, wish you good luck for your exams ;-) And thanks again for this plugin

**Comment by WummoFTW** [comment]
Is there any updates on the fix for this issue?

**Comment by g30r93g** [comment]
Finished my exams and university application. I have started a rewrite to make the plugin more stable and now that I have the time I'll be focusing on this.

**Comment by ValoV83** [comment]
Good to hear! Looking forward to you pushing the updated rewritten plugin when it's ready.

**Comment by g30r93g** [comment]
Hi all. I've rewritten all of it but have run into issues with getting the correct behaviours from the plugin. Combine this with [Antonio Meilreles's Vieramatic Plugin](https://github.com/AntonioMeireles/homebridge-vieramatic) which is a far better plugin than this one, it is hard to justify improving this plugin. I'll focus on opening a PR on homebridge-vieramatic and bringing any differences over to homebridge-vieramatic, but going forward I'll be archiving this plugin. Thanks all for the support for the last couple of years this plugin has been around for.
