### ISSUE TITLE
Siri don‘t work

### ISSUE THREAD

**Issue by LeBaron90** [g30r93g/homebridge-panasonic#6]
Everything works great, I can choose every input and turn on and off my panasonic tx75exw784. But when I want to use Siri to start netflix on my TV, Siri says, „one moment“ and nothing happens...

**Comment by g30r93g** [comment]
Hi! I've had similar issues with getting Siri to control the TV's inputs as well. I think this is more to do with iOS than the plugin itself, though I will have a look into it.

**Comment by LeBaron90** [comment]
Ok, maybe with the next iOS Update.

I'll stay tuned, great work - thank you!
