### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by ghost** [g30r93g/homebridge-panasonic#8]
delete

**Comment by g30r93g** [comment]
Hi! Thanks for letting me know, I'll have a look at it tonight and have it fixed soon. I've changed a library in the latest update so it might be to do with that.

**Comment by YRRK** [comment]
Hmm, i see you’ve updated it. Aldough on the NPMJS.Com it’s still called version 4.2.3 but I have 4.2.4 now.

Unfortunately it now crashes the Homebridge after starting: 


:(
With kind regards,



Op 10 mei 2019 om 16:32 heeft George Nick Gorzynski <notifications@github.com> het volgende geschreven:

Hi! Thanks for letting me know, I'll have a look at it tonight and have it fixed soon. I've changed a library in the latest update so it might be to do with that.

**Comment by YRRK** [comment]
In the previous version it did not crash normally at start. HDMI 1 & 2 worked. It only crashed the bridge when using inputs 5,6,7,8.

**Comment by g30r93g** [comment]
I've started having the same issue with `connect ECONNREFUSED 127.0.0.1:55000`. I'll take a deeper look.

**Comment by g30r93g** [comment]
Also, changing volume will be supported later in iOS from the Remote in control centre from what I've heard.

**Comment by g30r93g** [comment]
As far as inputs go, I have been able to switch HDMI inputs but not apps.

**Comment by g30r93g** [comment]
Okay. Version 4.2.9 fixes the ECONNREFUSED and the input switching. Hopefully it will fix it for you too.

**Comment by YRRK** [comment]
Yes thanks! Looking forward to zero the volume and back on for the home cinema from homekit.

**Comment by g30r93g** [comment]
The code for speaker control is there it’s just a matter of Apple making use of it.

**Comment by g30r93g** [comment]
Quick update: The speaker control is part of the AirPlay 2 protocol, but is exposed to HomeKit, so long as the speaker service is set up.
