### ISSUE TITLE
error wrong homebridge version

### ISSUE THREAD

**Issue by ColGren** [g30r93g/homebridge-panasonic#9]
Hello, I'm getting this error:

 Error: Plugin /usr/local/lib/node_modules/homebridge-panasonic-viera-tv requires a HomeBridge version of ^0.4.46 which does not satisfy the current HomeBridge version of 0.4.42. You may need to upgrade your installation of HomeBridge.
May 13 12:32:07 oldpi homebridge[305]:     at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:56:11)
May 13 12:32:07 oldpi homebridge[305]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:142:14)
May 13 12:32:07 oldpi homebridge[305]:     at Array.forEach (<anonymous>)
May 13 12:32:07 oldpi homebridge[305]:     at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:138:22)
May 13 12:32:07 oldpi homebridge[305]:     at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:24)
May 13 12:32:07 oldpi homebridge[305]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
May 13 12:32:07 oldpi homebridge[305]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
May 13 12:32:07 oldpi homebridge[305]:     at Module._compile (module.js:652:30)
May 13 12:32:07 oldpi homebridge[305]:     at Object.Module._extensions..js (module.js:663:10)
May 13 12:32:07 oldpi homebridge[305]:     at Module.load (module.js:565:32)
May 13 12:32:07 oldpi homebridge[305]:     at tryModuleLoad (module.js:505:12)
May 13 12:32:07 oldpi homebridge[305]:     at Function.Module._load (module.js:497:3)
May 13 12:32:07 oldpi homebridge[305]:     at Function.Module.runMain (module.js:693:10)
May 13 12:32:07 oldpi homebridge[305]:     at startup (bootstrap_node.js:191:16)
May 13 12:32:07 oldpi homebridge[305]:     at bootstrap_node.js:612:3

despite having globally updated homebridge

**Comment by LeBaron90** [comment]
try to delete homebridge and reinstall with the latest version. that worked for me.

**Comment by ColGren** [comment]
hasn't fixed the issue for me.. I'm running homebridge as a service does that make a difference?

**Comment by g30r93g** [comment]
Hi! It seems you're currently running home bridge on 0.4.42 which is below the 0.4.46 requirement for this plugin. Use `sudo npm install -g homebridge@0.4.49` to install the latest version (correct as of 15/05/19). The plugin should potentially work then

**Comment by g30r93g** [comment]
@ColGren is the issue still happening?

**Comment by ColGren** [comment]
Still not working after updating journalctl log below..

I does seem that somehow I'm still running an older version of homebridge - Could this be that I'm running homebridge as a service on my pi?

`May 17 12:30:57 oldpi systemd[1]: Started Node.js HomeKit Server.
May 17 12:31:01 oldpi homebridge[15420]: [2019-5-17 12:31:01] Loaded plugin: homebridge-hue
May 17 12:31:01 oldpi homebridge[15420]: [2019-5-17 12:31:01] Registering platform 'homebridge-hue.Hue'
May 17 12:31:01 oldpi homebridge[15420]: [2019-5-17 12:31:01] ---
May 17 12:31:01 oldpi homebridge[15420]: [2019-5-17 12:31:01] Loaded plugin: homebridge-lifx-lan
May 17 12:31:01 oldpi homebridge[15420]: [2019-5-17 12:31:01] Registering platform 'homebridge-lifx-lan.LifxLan'
May 17 12:31:01 oldpi homebridge[15420]: [2019-5-17 12:31:01] ---
May 17 12:31:02 oldpi homebridge[15420]: [2019-5-17 12:31:02] Loaded plugin: homebridge-nest
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] Registering platform 'homebridge-nest.Nest'
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] ---
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] ====================
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] ERROR LOADING PLUGIN homebridge-panasonic-viera-tv:
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] Error: Plugin /usr/local/lib/node_modules/homebridge-panasonic-viera-tv requires a HomeBridge version of ^0.4.46 which does not satisfy the current HomeBridge version of 0.4.42. You may need to upgrade your installation of HomeBridge.
May 17 12:31:03 oldpi homebridge[15420]:     at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:56:11)
May 17 12:31:03 oldpi homebridge[15420]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:142:14)
May 17 12:31:03 oldpi homebridge[15420]:     at Array.forEach (<anonymous>)
May 17 12:31:03 oldpi homebridge[15420]:     at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:138:22)
May 17 12:31:03 oldpi homebridge[15420]:     at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:24)
May 17 12:31:03 oldpi homebridge[15420]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
May 17 12:31:03 oldpi homebridge[15420]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
May 17 12:31:03 oldpi homebridge[15420]:     at Module._compile (module.js:652:30)
May 17 12:31:03 oldpi homebridge[15420]:     at Object.Module._extensions..js (module.js:663:10)
May 17 12:31:03 oldpi homebridge[15420]:     at Module.load (module.js:565:32)
May 17 12:31:03 oldpi homebridge[15420]:     at tryModuleLoad (module.js:505:12)
May 17 12:31:03 oldpi homebridge[15420]:     at Function.Module._load (module.js:497:3)
May 17 12:31:03 oldpi homebridge[15420]:     at Function.Module.runMain (module.js:693:10)
May 17 12:31:03 oldpi homebridge[15420]:     at startup (bootstrap_node.js:191:16)
May 17 12:31:03 oldpi homebridge[15420]:     at bootstrap_node.js:612:3
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] ====================
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] Loaded config.json with 1 accessories and 3 platforms.
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] ---
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] Loading 3 platforms...
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] [LIFX] Initializing LifxLan platform...
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] [Hue] Initializing Hue platform...
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] [Hue] homebridge-hue v0.9.4, node v8.11.2, homebridge v0.4.42
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] [Nest] Initializing Nest platform...
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] [Nest] Fetching Nest devices.
May 17 12:31:03 oldpi homebridge[15420]: [2019-5-17 12:31:03] Loading 1 accessories...
May 17 12:31:03 oldpi homebridge[15420]: /usr/lib/node_modules/homebridge/lib/api.js:64
May 17 12:31:03 oldpi homebridge[15420]:       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
May 17 12:31:03 oldpi homebridge[15420]:       ^
May 17 12:31:03 oldpi homebridge[15420]: Error: The requested accessory 'Panasonic-TV' was not registered by any plugin.
May 17 12:31:03 oldpi homebridge[15420]:     at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
May 17 12:31:03 oldpi homebridge[15420]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
May 17 12:31:03 oldpi homebridge[15420]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
May 17 12:31:03 oldpi homebridge[15420]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
May 17 12:31:03 oldpi homebridge[15420]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
May 17 12:31:03 oldpi homebridge[15420]:     at Module._compile (module.js:652:30)
May 17 12:31:03 oldpi homebridge[15420]:     at Object.Module._extensions..js (module.js:663:10)
May 17 12:31:03 oldpi homebridge[15420]:     at Module.load (module.js:565:32)
May 17 12:31:03 oldpi homebridge[15420]:     at tryModuleLoad (module.js:505:12)
May 17 12:31:03 oldpi homebridge[15420]:     at Function.Module._load (module.js:497:3)
May 17 12:31:03 oldpi homebridge[15420]:     at Function.Module.runMain (module.js:693:10)
May 17 12:31:03 oldpi homebridge[15420]:     at startup (bootstrap_node.js:191:16)
May 17 12:31:03 oldpi homebridge[15420]:     at bootstrap_node.js:612:3
May 17 12:31:03 oldpi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
May 17 12:31:03 oldpi systemd[1]: homebridge.service: Unit entered failed state.
May 17 12:31:03 oldpi systemd[1]: homebridge.service: Failed with result 'exit-code'.`

**Comment by g30r93g** [comment]
Yes you're still on 0.4.42 (`Error: Plugin /usr/local/lib/node_modules/homebridge-panasonic-viera-tv requires a HomeBridge version of ^0.4.46 which does not satisfy the current HomeBridge version of 0.4.42. You may need to upgrade your installation of HomeBridge.`)
Please enter `sudo npm install -g homebridge@0.4.49` into your device's command line.

**Comment by ColGren** [comment]
finally found rogue instance of homebridge running which wouldn't uninstall using sudo npm -g uninstall homebridge

All working now - many thanks

**Comment by g30r93g** [comment]
Great! Thank you
